# Generated by Django 3.2.3 on 2021-08-07 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myapp.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0016_auto_20210406_1219'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='allDevices',
            fields=[
                ('d_id', models.CharField(default=0, max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='flat',
            fields=[
                ('flt_id', models.CharField(default=myapp.utils.create_new_ref_number, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('flt_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='floor',
            fields=[
                ('f_id', models.CharField(default=myapp.utils.create_new_ref_number, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('f_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='otptemplogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10)),
                ('otp', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='place',
            fields=[
                ('p_id', models.CharField(default=myapp.utils.create_new_ref_number, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('p_type', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('r_id', models.CharField(default=myapp.utils.create_new_ref_number, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('r_name', models.CharField(max_length=15)),
                ('flt_id', models.ForeignKey(default=1, max_length=10, on_delete=django.db.models.deletion.CASCADE, to='myapp.flat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SomeModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('file', models.CharField(blank=True, max_length=499999)),
            ],
        ),
        migrations.CreateModel(
            name='subuseraccess',
            fields=[
                ('emailtest', models.EmailField(max_length=254)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='tempUserVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10)),
                ('otp', models.CharField(blank=True, default=myapp.utils.otplogin, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='userimages',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('images', models.ImageField(blank=True, upload_to='profile_picture')),
            ],
        ),
        migrations.CreateModel(
            name='deviceIpAddress',
            fields=[
                ('d_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.alldevices')),
                ('ipaddress', models.CharField(blank=True, max_length=99, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='deviceStatus',
            fields=[
                ('d_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.alldevices')),
                ('pin1Status', models.IntegerField(blank=True, null=True)),
                ('pin2Status', models.IntegerField(blank=True, null=True)),
                ('pin3Status', models.IntegerField(blank=True, null=True)),
                ('pin4Status', models.IntegerField(blank=True, null=True)),
                ('pin5Status', models.IntegerField(blank=True, null=True)),
                ('pin6Status', models.IntegerField(blank=True, null=True)),
                ('pin7Status', models.IntegerField(blank=True, null=True)),
                ('pin8Status', models.IntegerField(blank=True, null=True)),
                ('pin9Status', models.IntegerField(blank=True, null=True)),
                ('pin10Status', models.IntegerField(blank=True, null=True)),
                ('pin11Status', models.IntegerField(blank=True, null=True)),
                ('pin12Status', models.IntegerField(blank=True, null=True)),
                ('pin13Status', models.IntegerField(blank=True, null=True)),
                ('pin14Status', models.IntegerField(blank=True, null=True)),
                ('pin15Status', models.IntegerField(blank=True, null=True)),
                ('pin16Status', models.IntegerField(blank=True, null=True)),
                ('pin17Status', models.IntegerField(blank=True, null=True)),
                ('pin18Status', models.IntegerField(blank=True, null=True)),
                ('pin19Status', models.CharField(blank=True, max_length=100, null=True)),
                ('pin20Status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pinName',
            fields=[
                ('d_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.alldevices')),
                ('pin1Name', models.CharField(blank=True, max_length=20, null=True)),
                ('pin2Name', models.CharField(blank=True, max_length=20, null=True)),
                ('pin3Name', models.CharField(blank=True, max_length=20, null=True)),
                ('pin4Name', models.CharField(blank=True, max_length=20, null=True)),
                ('pin5Name', models.CharField(blank=True, max_length=20, null=True)),
                ('pin6Name', models.CharField(blank=True, max_length=20, null=True)),
                ('pin7Name', models.CharField(blank=True, max_length=20, null=True)),
                ('pin8Name', models.CharField(blank=True, max_length=20, null=True)),
                ('pin9Name', models.CharField(blank=True, max_length=20, null=True)),
                ('pin10Name', models.CharField(blank=True, max_length=20, null=True)),
                ('pin11Name', models.CharField(blank=True, max_length=20, null=True)),
                ('pin12Name', models.CharField(blank=True, max_length=20, null=True)),
                ('pin13Name', models.CharField(blank=True, max_length=20, null=True)),
                ('pin14Name', models.CharField(blank=True, max_length=20, null=True)),
                ('pin15Name', models.CharField(blank=True, max_length=20, null=True)),
                ('pin16Name', models.CharField(blank=True, max_length=20, null=True)),
                ('pin17Name', models.CharField(blank=True, max_length=20, null=True)),
                ('pin18Name', models.CharField(blank=True, max_length=20, null=True)),
                ('pin19Name', models.CharField(blank=True, max_length=20, null=True)),
                ('pin20Name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sensors',
            fields=[
                ('d_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.alldevices')),
                ('sensor1', models.FloatField(blank=True, default=0.0, max_length=50)),
                ('sensor2', models.FloatField(blank=True, default=0.0, max_length=50)),
                ('sensor3', models.FloatField(blank=True, default=0.0, max_length=50)),
                ('sensor4', models.FloatField(blank=True, default=0.0, max_length=50)),
                ('sensor5', models.FloatField(blank=True, default=0.0, max_length=50)),
                ('sensor6', models.FloatField(blank=True, default=0.0, max_length=50)),
                ('sensor7', models.FloatField(blank=True, default=0.0, max_length=50)),
                ('sensor8', models.FloatField(blank=True, default=0.0, max_length=50)),
                ('sensor9', models.FloatField(blank=True, default=0.0, max_length=50)),
                ('sensor10', models.FloatField(blank=True, default=0.0, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ssidPassword',
            fields=[
                ('d_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.alldevices')),
                ('ssid1', models.CharField(blank=True, max_length=15, unique=True)),
                ('password1', models.CharField(blank=True, max_length=50)),
                ('ssid2', models.CharField(blank=True, max_length=15, unique=True)),
                ('password2', models.CharField(blank=True, max_length=50)),
                ('ssid3', models.CharField(blank=True, max_length=15, unique=True)),
                ('password3', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tempuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(default='2000-01-01', null=True)),
                ('timing', models.TimeField(default='00:00')),
                ('d_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.alldevices')),
                ('f_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.floor')),
                ('flt_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.flat')),
                ('p_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.place')),
                ('r_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='subuserplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subuseraccess')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pinschedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField(default='2000-01-01', null=True)),
                ('timing1', models.TimeField(default='00:00')),
                ('pin1Status', models.IntegerField(blank=True, null=True)),
                ('pin2Status', models.IntegerField(blank=True, null=True)),
                ('pin3Status', models.IntegerField(blank=True, null=True)),
                ('pin4Status', models.IntegerField(blank=True, null=True)),
                ('pin5Status', models.IntegerField(blank=True, null=True)),
                ('pin6Status', models.IntegerField(blank=True, null=True)),
                ('pin7Status', models.IntegerField(blank=True, null=True)),
                ('pin8Status', models.IntegerField(blank=True, null=True)),
                ('pin9Status', models.IntegerField(blank=True, null=True)),
                ('pin10Status', models.IntegerField(blank=True, null=True)),
                ('pin11Status', models.IntegerField(blank=True, null=True)),
                ('pin12Status', models.IntegerField(blank=True, null=True)),
                ('pin13Status', models.IntegerField(blank=True, null=True)),
                ('pin14Status', models.IntegerField(blank=True, null=True)),
                ('pin15Status', models.IntegerField(blank=True, null=True)),
                ('pin16Status', models.IntegerField(blank=True, null=True)),
                ('pin17Status', models.IntegerField(blank=True, null=True)),
                ('pin18Status', models.IntegerField(blank=True, null=True)),
                ('pin19Status', models.CharField(blank=True, max_length=100, null=True)),
                ('pin20Status', models.CharField(blank=True, max_length=100, null=True)),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.alldevices')),
            ],
        ),
        migrations.AddField(
            model_name='floor',
            name='p_id',
            field=models.ForeignKey(default=1, max_length=10, on_delete=django.db.models.deletion.CASCADE, to='myapp.place'),
        ),
        migrations.AddField(
            model_name='floor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flat',
            name='f_id',
            field=models.ForeignKey(default=1, max_length=10, on_delete=django.db.models.deletion.CASCADE, to='myapp.floor'),
        ),
        migrations.AddField(
            model_name='flat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_installed', models.DateField(default=myapp.utils.dt)),
                ('d_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.alldevices')),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='emergencyNumber',
            fields=[
                ('d_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.alldevices')),
                ('number1', models.CharField(max_length=12, null=True)),
                ('number2', models.CharField(max_length=12, null=True)),
                ('number3', models.CharField(max_length=12, null=True)),
                ('number4', models.CharField(max_length=12, null=True)),
                ('number5', models.CharField(max_length=12, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
