# Generated by Django 3.1.1 on 2021-09-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneyeardata',
            name='d_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
