# Generated by Django 3.1.1 on 2021-09-07 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='energy',
            fields=[
                ('d_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.alldevices')),
                ('enrgy10', models.CharField(blank=True, max_length=50)),
                ('enrgy20', models.CharField(blank=True, max_length=50)),
                ('enrgy30', models.CharField(blank=True, max_length=50)),
                ('enrgy40', models.CharField(blank=True, max_length=50)),
                ('enrgy50', models.CharField(blank=True, max_length=50)),
                ('enrgy60', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
