# Generated by Django 4.0.5 on 2022-07-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='timing',
            field=models.CharField(default='00:00', max_length=200),
        ),
    ]
