# Generated by Django 3.1.1 on 2021-09-08 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_energy'),
    ]

    operations = [
        migrations.CreateModel(
            name='oneHourEnergy',
            fields=[
                ('d_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.energy')),
                ('hour1', models.IntegerField(blank=True, default=0)),
                ('hour2', models.IntegerField(blank=True, default=0)),
                ('hour3', models.IntegerField(blank=True, default=0)),
                ('hour4', models.IntegerField(blank=True, default=0)),
                ('hour5', models.IntegerField(blank=True, default=0)),
                ('hour6', models.IntegerField(blank=True, default=0)),
                ('hour7', models.IntegerField(blank=True, default=0)),
                ('hour8', models.IntegerField(blank=True, default=0)),
                ('hour9', models.IntegerField(blank=True, default=0)),
                ('hour10', models.IntegerField(blank=True, default=0)),
                ('hour11', models.IntegerField(blank=True, default=0)),
                ('hour12', models.IntegerField(blank=True, default=0)),
                ('hour13', models.IntegerField(blank=True, default=0)),
                ('hour14', models.IntegerField(blank=True, default=0)),
                ('hour15', models.IntegerField(blank=True, default=0)),
                ('hour16', models.IntegerField(blank=True, default=0)),
                ('hour17', models.IntegerField(blank=True, default=0)),
                ('hour18', models.IntegerField(blank=True, default=0)),
                ('hour19', models.IntegerField(blank=True, default=0)),
                ('hour20', models.IntegerField(blank=True, default=0)),
                ('hour21', models.IntegerField(blank=True, default=0)),
                ('hour22', models.IntegerField(blank=True, default=0)),
                ('hour23', models.IntegerField(blank=True, default=0)),
                ('hour24', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
