# Generated by Django 4.0.5 on 2022-07-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_pinname_pin10name_alter_pinname_pin11name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinname',
            name='pin10Name',
            field=models.CharField(blank=True, default='Device10,001', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pinname',
            name='pin11Name',
            field=models.CharField(blank=True, default='Device11,001', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pinname',
            name='pin12Name',
            field=models.CharField(blank=True, default='Device12,001', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pinname',
            name='pin13Name',
            field=models.CharField(blank=True, default='Device13,001', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pinname',
            name='pin14Name',
            field=models.CharField(blank=True, default='Device14,001', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pinname',
            name='pin15Name',
            field=models.CharField(blank=True, default='Device15,001', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pinname',
            name='pin16Name',
            field=models.CharField(blank=True, default='Device16,001', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pinname',
            name='pin17Name',
            field=models.CharField(blank=True, default='Device17,001', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pinname',
            name='pin18Name',
            field=models.CharField(blank=True, default='Device18,001', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pinname',
            name='pin19Name',
            field=models.CharField(blank=True, default='Device19,001', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pinname',
            name='pin1Name',
            field=models.CharField(blank=True, default='Device1,001', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pinname',
            name='pin20Name',
            field=models.CharField(blank=True, default='Device20,001', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pinname',
            name='pin2Name',
            field=models.CharField(blank=True, default='Device2,001', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pinname',
            name='pin3Name',
            field=models.CharField(blank=True, default='Device3,001', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pinname',
            name='pin4Name',
            field=models.CharField(blank=True, default='Device4,001', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pinname',
            name='pin5Name',
            field=models.CharField(blank=True, default='Device5,001', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pinname',
            name='pin6Name',
            field=models.CharField(blank=True, default='Device6,001', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pinname',
            name='pin7Name',
            field=models.CharField(blank=True, default='Device7,001', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pinname',
            name='pin8Name',
            field=models.CharField(blank=True, default='Device8,001', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pinname',
            name='pin9Name',
            field=models.CharField(blank=True, default='Device9,001', max_length=20, null=True),
        ),
    ]
