# Generated by Django 3.1.1 on 2021-09-08 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_onehourenergy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onehourenergy',
            name='d_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.alldevices'),
        ),
    ]
