# Generated by Django 3.1.1 on 2021-09-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210908_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onehourenergy',
            name='d_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
