# Generated by Django 3.1.1 on 2021-10-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210930_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='energy',
            name='datee',
            field=models.DateField(default='2000-01-01', null=True),
        ),
        migrations.AddField(
            model_name='energy',
            name='timinge',
            field=models.TimeField(default='00:00'),
        ),
    ]
