# Generated by Django 3.1.1 on 2021-10-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20211006_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energy',
            name='datee',
        ),
        migrations.RemoveField(
            model_name='energy',
            name='timinge',
        ),
    ]
