# Generated by Django 3.1.1 on 2021-09-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_oneyeardata'),
    ]

    operations = [
        migrations.CreateModel(
            name='threeyears',
            fields=[
                ('d_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('year1', models.CharField(max_length=50)),
                ('year2', models.CharField(max_length=50)),
                ('year3', models.CharField(max_length=50)),
            ],
        ),
    ]
