from django.db import models
from django.db.models.expressions import F
from django.db.models.fields import CharField, EmailField
# from embed_video.fields import EmbedVideoField
from rest_framework import serializers
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
import math, random
import requests
import os
from rest_framework.decorators import action
from twilio.rest import Client, TwilioIpMessagingClient
from myapp.utils import create_new_ref_number, dt, otplogin, defprofoto
from datetime import date
# User._meta.get_field('email')._unique = True


device_categories = (
    (1, u'Fan'),
    (2, u'Light'),
    (3, u'Plug'),
    (4, u'TV'),
    (5, u'Gyeser'),
    (6, u'Others'),
    # (7, u'')
)


smart_device = (
    (1, u'Yes'),
    (2, u'No'),
)


class place(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    p_id = models.CharField(max_length = 10,blank=False,unique=True,primary_key=True,default=create_new_ref_number)
    p_type = models.CharField(max_length=15)

class floor(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    p_id = models.ForeignKey(place, max_length=10, null=False, default=1,on_delete=models.CASCADE)
    f_id = models.CharField(max_length = 10, blank=False,unique=True,primary_key=True,default=create_new_ref_number)
    f_name = models.CharField(max_length=15)

class flat(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    f_id = models.ForeignKey(floor, max_length=10, null=False, default=1,on_delete=models.CASCADE)
    flt_id = models.CharField(max_length = 10, blank=False,unique=True,primary_key=True,default=create_new_ref_number)
    flt_name = models.CharField(max_length=15)
    

class room(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    flt_id = models.ForeignKey(flat, max_length=10, null=False, default=1, on_delete=models.CASCADE)
    r_id = models.CharField(max_length = 10,blank=False,unique=True,primary_key=True,default=create_new_ref_number)
    r_name = models.CharField(max_length=15)

class allDevices(models.Model):
    d_id = models.CharField(max_length=40, default=0,primary_key=True)

class device(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    r_id = models.ForeignKey(room, on_delete=models.CASCADE)
    d_id = models.OneToOneField(allDevices, on_delete=models.CASCADE)
    date_installed = models.DateField(default=dt)

class deviceStatus(models.Model):
    d_id = models.OneToOneField(allDevices, on_delete=models.CASCADE,primary_key=True)
    pin1Status = models.IntegerField(blank=True,null=True)
    pin2Status = models.IntegerField(blank=True,null=True)
    pin3Status = models.IntegerField(blank=True,null=True)
    pin4Status = models.IntegerField(blank=True,null=True)
    pin5Status = models.IntegerField(blank=True,null=True)
    pin6Status = models.IntegerField(blank=True,null=True)
    pin7Status = models.IntegerField(blank=True,null=True)
    pin8Status = models.IntegerField(blank=True,null=True)
    pin9Status = models.IntegerField(blank=True,null=True)
    pin10Status = models.IntegerField(blank=True,null=True)
    pin11Status = models.IntegerField(blank=True,null=True)
    pin12Status = models.IntegerField(blank=True,null=True)
    pin13Status = models.IntegerField(blank=True,null=True)
    pin14Status = models.IntegerField(blank=True,null=True)
    pin15Status = models.IntegerField(blank=True,null=True)
    pin16Status = models.IntegerField(blank=True,null=True)
    pin17Status = models.BigIntegerField(blank=True,null=True)
    pin18Status = models.IntegerField(blank=True,null=True)
    pin19Status = models.CharField(blank=True,null=True,max_length=100)
    pin20Status = models.CharField(blank=True,null=True,max_length=100)


class sensors(models.Model):
    d_id = models.OneToOneField(allDevices, on_delete=models.CASCADE,primary_key=True)
    sensor1 = models.FloatField(unique = False, max_length=50,default=0.0, blank=True)
    sensor2 = models.FloatField(unique = False, max_length=50,default=0.0, blank=True)
    sensor3 = models.FloatField(unique = False, max_length=50,default=0.0, blank=True)
    sensor4 = models.FloatField(unique = False, max_length=50,default=0.0, blank=True)
    sensor5 = models.FloatField(unique = False, max_length=50,default=0.0, blank=True)
    sensor6 = models.FloatField(unique = False, max_length=50,default=0.0, blank=True)
    sensor7 = models.FloatField(unique = False, max_length=50,default=0.0, blank=True)
    sensor8 = models.FloatField(unique = False, max_length=50,default=0.0, blank=True)
    sensor9 = models.FloatField(unique = False, max_length=50,default=0.0, blank=True)
    sensor10 = models.FloatField(unique = False, max_length=50,default=0.0, blank=True)

class ssidPassword(models.Model):
    d_id = models.OneToOneField(allDevices, on_delete=models.CASCADE,primary_key=True)
    ssid1 = models.CharField(unique=True, max_length=15,blank=True)
    password1 = models.CharField(null=False, max_length=50,blank=True)
    ssid2 = models.CharField(unique=True, max_length=15,blank=True)
    password2 = models.CharField(null=False, max_length=50,blank=True)
    ssid3 = models.CharField(unique=True, max_length=15,blank=True)
    password3 = models.CharField(null=False, max_length=50,blank=True)

class emergencyNumber(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    d_id = models.OneToOneField(allDevices, on_delete=models.CASCADE,primary_key=True)
    number1 = models.CharField(null=True, max_length=12)
    number2 = models.CharField(null=True, max_length=12)
    number3 = models.CharField(null=True, max_length=12)
    number4 = models.CharField(null=True, max_length=12)
    number5 = models.CharField(null=True, max_length=12)

class pinName(models.Model):
    d_id = models.OneToOneField(allDevices, on_delete=models.CASCADE,primary_key=True)
    pin1Name = models.CharField(blank=True,null=True,max_length=20)
    pin2Name = models.CharField(blank=True,null=True,max_length=20)
    pin3Name = models.CharField(blank=True,null=True,max_length=20)
    pin4Name = models.CharField(blank=True,null=True,max_length=20)
    pin5Name = models.CharField(blank=True,null=True,max_length=20)
    pin6Name = models.CharField(blank=True,null=True,max_length=20)
    pin7Name = models.CharField(blank=True,null=True,max_length=20)
    pin8Name = models.CharField(blank=True,null=True,max_length=20)
    pin9Name = models.CharField(blank=True,null=True,max_length=20)
    pin10Name = models.CharField(blank=True,null=True,max_length=20)
    pin11Name = models.CharField(blank=True,null=True,max_length=20)
    pin12Name = models.CharField(blank=True,null=True,max_length=20)
    pin13Name = models.CharField(blank=True,null=True,max_length=20)
    pin14Name = models.CharField(blank=True,null=True,max_length=20)
    pin15Name = models.CharField(blank=True,null=True,max_length=20)
    pin16Name = models.CharField(blank=True,null=True,max_length=20)
    pin17Name = models.CharField(blank=True,null=True,max_length=20)
    pin18Name = models.CharField(blank=True,null=True,max_length=20)
    pin19Name = models.CharField(blank=True,null=True,max_length=20)
    pin20Name = models.CharField(blank=True,null=True,max_length=20)


class pinschedule(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    d_id = models.ForeignKey(allDevices, on_delete=models.CASCADE)
    date1 = models.DateField(default="2000-01-01",null=True)
    timing1 = models.TimeField(default='00:00')
    pin1Status = models.IntegerField(blank=True,null=True)
    pin2Status = models.IntegerField(blank=True,null=True)
    pin3Status = models.IntegerField(blank=True,null=True)
    pin4Status = models.IntegerField(blank=True,null=True)
    pin5Status = models.IntegerField(blank=True,null=True)
    pin6Status = models.IntegerField(blank=True,null=True)
    pin7Status = models.IntegerField(blank=True,null=True)
    pin8Status = models.IntegerField(blank=True,null=True)
    pin9Status = models.IntegerField(blank=True,null=True)
    pin10Status = models.IntegerField(blank=True,null=True)
    pin11Status = models.IntegerField(blank=True,null=True)
    pin12Status = models.IntegerField(blank=True,null=True)
    pin13Status = models.IntegerField(blank=True,null=True)
    pin14Status = models.IntegerField(blank=True,null=True)
    pin15Status = models.IntegerField(blank=True,null=True)
    pin16Status = models.IntegerField(blank=True,null=True)
    pin17Status = models.BigIntegerField(blank=True,null=True)
    pin18Status = models.IntegerField(blank=True,null=True)
    pin19Status = models.CharField(blank=True,null=True,max_length=100)
    pin20Status = models.CharField(blank=True,null=True,max_length=100)
   

class userimages(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,primary_key=True)
    images = models.ImageField(upload_to='profile_picture', blank=True)

class SomeModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,primary_key=True)
    file = models.CharField(max_length=499999, blank=True, default=defprofoto())

class deviceIpAddress(models.Model):
    d_id = models.OneToOneField(allDevices, on_delete=models.CASCADE,primary_key=True)
    ipaddress = models.CharField(max_length=99,blank=True,null=True)


class subuseraccess(models.Model):
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    emailtest = EmailField()
    email = models.CharField(primary_key=True, max_length=100)

class subuserplace(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    owner_name = models.CharField(max_length=20, blank=True)
    name = models.CharField(max_length=100, blank=False)
    email = models.ForeignKey(subuseraccess, on_delete=models.CASCADE)
    p_id = models.ForeignKey(place, on_delete=models.CASCADE)



# class Profile(models.Model):
#     # user = models.OneToOneField(User ,on_delete=models.CASCADE)
#     mobile = models.CharField(max_length=20)
#     otp = models.CharField(max_length=6)


# API for main user include all the parameters while creating new temporary user
# API for temporary user include only mobile or email with place, floor, room, device ID's

class tempuser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    owner_name = models.CharField(max_length=20, blank=True)
    mobile = models.CharField(max_length=10, blank=True)
    email = EmailField(blank=True)
    name = models.CharField(max_length=100,blank=False)
    date = models.DateField(default="2000-01-01",null=True)
    timing = models.TimeField(default='00:00')
    p_id = models.ForeignKey(place, on_delete=models.CASCADE, blank=True, null=True)
    f_id = models.ForeignKey(floor, on_delete=models.CASCADE, blank=True, null=True)
    flt_id = models.ForeignKey(flat, on_delete=models.CASCADE, blank=True, null=True)
    r_id = models.ForeignKey(room, on_delete=models.CASCADE, blank=True, null=True)
    d_id = models.ForeignKey(allDevices, on_delete=models.CASCADE, blank=True, null=True)

class tempUserVerification(models.Model):
    mobile = models.CharField(max_length=10, blank=False)
    # updated_date = models.DateField(auto_now_add=True)
    # updated_time = models.TimeField(auto_now=True,editable=True)
    otp = models.CharField(max_length=6, default=otplogin, blank=True)    

class otptemplogin(models.Model):
    mobile = models.CharField(max_length=10, blank=False)
    otp = models.CharField(max_length=6, blank=False)

class energy(models.Model):
    d_id = models.OneToOneField(allDevices, on_delete=models.CASCADE,primary_key=True)
    enrgy10 = models.CharField(max_length=50, blank=True)
    enrgy20 = models.CharField(max_length=50, blank=True)
    enrgy30 = models.CharField(max_length=50, blank=True)
    enrgy40 = models.CharField(max_length=50, blank=True)
    enrgy50 = models.CharField(max_length=50, blank=True)
    enrgy60 = models.CharField(max_length=50, blank=True)

class oneHourEnergy(models.Model):
    d_id = models.CharField(max_length=50, primary_key=True)
    hour1 = models.CharField(default=0, blank=True, max_length=10)
    hour2 = models.CharField(default=0, blank=True, max_length=10)
    hour3 = models.CharField(default=0, blank=True, max_length=10)
    hour4 = models.CharField(default=0, blank=True, max_length=10)
    hour5 = models.CharField(default=0, blank=True, max_length=10)
    hour6 = models.CharField(default=0, blank=True, max_length=10)
    hour7 = models.CharField(default=0, blank=True, max_length=10)
    hour8 = models.CharField(default=0, blank=True, max_length=10)
    hour9 = models.CharField(default=0, blank=True, max_length=10)
    hour10 = models.CharField(default=0, blank=True, max_length=10)
    hour11 = models.CharField(default=0, blank=True, max_length=10)
    hour12 = models.CharField(default=0, blank=True, max_length=10)
    hour13 = models.CharField(default=0, blank=True, max_length=10)
    hour14 = models.CharField(default=0, blank=True, max_length=10)
    hour15 = models.CharField(default=0, blank=True, max_length=10)
    hour16 = models.CharField(default=0, blank=True, max_length=10)
    hour17 = models.CharField(default=0, blank=True, max_length=10)
    hour18 = models.CharField(default=0, blank=True, max_length=10)
    hour19 = models.CharField(default=0, blank=True, max_length=10)
    hour20 = models.CharField(default=0, blank=True, max_length=10)
    hour21 = models.CharField(default=0, blank=True, max_length=10)
    hour22 = models.CharField(default=0, blank=True, max_length=10)
    hour23 = models.CharField(default=0, blank=True, max_length=10)
    hour24 = models.CharField(default=0, blank=True, max_length=10)

class oneyeardata(models.Model):
    d_id = models.CharField(max_length=50, primary_key=True)
    day1 = models.CharField(max_length=20, blank=True)
    day2 = models.CharField(max_length=20, blank=True)
    day3 = models.CharField(max_length=20, blank=True)
    day4 = models.CharField(max_length=20, blank=True)
    day5 = models.CharField(max_length=20, blank=True)
    day6 = models.CharField(max_length=20, blank=True)
    day7 = models.CharField(max_length=20, blank=True)
    day8 = models.CharField(max_length=20, blank=True)
    day9 = models.CharField(max_length=20, blank=True)
    day10 = models.CharField(max_length=20, blank=True)
    day11 = models.CharField(max_length=20, blank=True)
    day12 = models.CharField(max_length=20, blank=True)
    day13 = models.CharField(max_length=20, blank=True)
    day14 = models.CharField(max_length=20, blank=True)
    day15 = models.CharField(max_length=20, blank=True)
    day16 = models.CharField(max_length=20, blank=True)
    day17 = models.CharField(max_length=20, blank=True)
    day18 = models.CharField(max_length=20, blank=True)
    day19 = models.CharField(max_length=20, blank=True)
    day20 = models.CharField(max_length=20, blank=True)
    day21 = models.CharField(max_length=20, blank=True)
    day22 = models.CharField(max_length=20, blank=True)
    day23 = models.CharField(max_length=20, blank=True)
    day24 = models.CharField(max_length=20, blank=True)
    day25 = models.CharField(max_length=20, blank=True)
    day26 = models.CharField(max_length=20, blank=True)
    day27 = models.CharField(max_length=20, blank=True)
    day28 = models.CharField(max_length=20, blank=True)
    day29 = models.CharField(max_length=20, blank=True)
    day30 = models.CharField(max_length=20, blank=True)
    day31 = models.CharField(max_length=20, blank=True)
    day32 = models.CharField(max_length=20, blank=True)
    day33 = models.CharField(max_length=20, blank=True)
    day34 = models.CharField(max_length=20, blank=True)
    day35 = models.CharField(max_length=20, blank=True)
    day36 = models.CharField(max_length=20, blank=True)
    day37 = models.CharField(max_length=20, blank=True)
    day38 = models.CharField(max_length=20, blank=True)
    day39 = models.CharField(max_length=20, blank=True)
    day40 = models.CharField(max_length=20, blank=True)
    day41 = models.CharField(max_length=20, blank=True)
    day42 = models.CharField(max_length=20, blank=True)
    day43 = models.CharField(max_length=20, blank=True)
    day44 = models.CharField(max_length=20, blank=True)
    day45 = models.CharField(max_length=20, blank=True)
    day46 = models.CharField(max_length=20, blank=True)
    day47 = models.CharField(max_length=20, blank=True)
    day48 = models.CharField(max_length=20, blank=True)
    day49 = models.CharField(max_length=20, blank=True)
    day50 = models.CharField(max_length=20, blank=True)
    day51 = models.CharField(max_length=20, blank=True)
    day52 = models.CharField(max_length=20, blank=True)
    day53 = models.CharField(max_length=20, blank=True)
    day54 = models.CharField(max_length=20, blank=True)
    day55 = models.CharField(max_length=20, blank=True)
    day56 = models.CharField(max_length=20, blank=True)
    day57 = models.CharField(max_length=20, blank=True)
    day58 = models.CharField(max_length=20, blank=True)
    day59 = models.CharField(max_length=20, blank=True)
    day60 = models.CharField(max_length=20, blank=True)
    day61 = models.CharField(max_length=20, blank=True)
    day62 = models.CharField(max_length=20, blank=True)
    day63 = models.CharField(max_length=20, blank=True)
    day64 = models.CharField(max_length=20, blank=True)
    day65 = models.CharField(max_length=20, blank=True)
    day66 = models.CharField(max_length=20, blank=True)
    day67 = models.CharField(max_length=20, blank=True)
    day68 = models.CharField(max_length=20, blank=True)
    day69 = models.CharField(max_length=20, blank=True)
    day70 = models.CharField(max_length=20, blank=True)
    day71 = models.CharField(max_length=20, blank=True)
    day72 = models.CharField(max_length=20, blank=True)
    day73 = models.CharField(max_length=20, blank=True)
    day74 = models.CharField(max_length=20, blank=True)
    day75 = models.CharField(max_length=20, blank=True)
    day76 = models.CharField(max_length=20, blank=True)
    day77 = models.CharField(max_length=20, blank=True)
    day78 = models.CharField(max_length=20, blank=True)
    day79 = models.CharField(max_length=20, blank=True)
    day80 = models.CharField(max_length=20, blank=True)
    day81 = models.CharField(max_length=20, blank=True)
    day82 = models.CharField(max_length=20, blank=True)
    day83 = models.CharField(max_length=20, blank=True)
    day84 = models.CharField(max_length=20, blank=True)
    day85 = models.CharField(max_length=20, blank=True)
    day86 = models.CharField(max_length=20, blank=True)
    day87 = models.CharField(max_length=20, blank=True)
    day88 = models.CharField(max_length=20, blank=True)
    day89 = models.CharField(max_length=20, blank=True)
    day90 = models.CharField(max_length=20, blank=True)
    day91 = models.CharField(max_length=20, blank=True)
    day92 = models.CharField(max_length=20, blank=True)
    day93 = models.CharField(max_length=20, blank=True)
    day94 = models.CharField(max_length=20, blank=True)
    day95 = models.CharField(max_length=20, blank=True)
    day96 = models.CharField(max_length=20, blank=True)
    day97 = models.CharField(max_length=20, blank=True)
    day98 = models.CharField(max_length=20, blank=True)
    day99 = models.CharField(max_length=20, blank=True)
    day100 = models.CharField(max_length=20, blank=True)
    day101 = models.CharField(max_length=20, blank=True)
    day102 = models.CharField(max_length=20, blank=True)
    day103 = models.CharField(max_length=20, blank=True)
    day104 = models.CharField(max_length=20, blank=True)
    day105 = models.CharField(max_length=20, blank=True)
    day106 = models.CharField(max_length=20, blank=True)
    day107 = models.CharField(max_length=20, blank=True)
    day108 = models.CharField(max_length=20, blank=True)
    day109 = models.CharField(max_length=20, blank=True)
    day110 = models.CharField(max_length=20, blank=True)
    day111 = models.CharField(max_length=20, blank=True)
    day112 = models.CharField(max_length=20, blank=True)
    day113 = models.CharField(max_length=20, blank=True)
    day114 = models.CharField(max_length=20, blank=True)
    day115 = models.CharField(max_length=20, blank=True)
    day116 = models.CharField(max_length=20, blank=True)
    day117 = models.CharField(max_length=20, blank=True)
    day118 = models.CharField(max_length=20, blank=True)
    day119 = models.CharField(max_length=20, blank=True)
    day120 = models.CharField(max_length=20, blank=True)
    day121 = models.CharField(max_length=20, blank=True)
    day122 = models.CharField(max_length=20, blank=True)
    day123 = models.CharField(max_length=20, blank=True)
    day124 = models.CharField(max_length=20, blank=True)
    day125 = models.CharField(max_length=20, blank=True)
    day126 = models.CharField(max_length=20, blank=True)
    day127 = models.CharField(max_length=20, blank=True)
    day128 = models.CharField(max_length=20, blank=True)
    day129 = models.CharField(max_length=20, blank=True)
    day130 = models.CharField(max_length=20, blank=True)
    day131 = models.CharField(max_length=20, blank=True)
    day132 = models.CharField(max_length=20, blank=True)
    day133 = models.CharField(max_length=20, blank=True)
    day134 = models.CharField(max_length=20, blank=True)
    day135 = models.CharField(max_length=20, blank=True)
    day136 = models.CharField(max_length=20, blank=True)
    day137 = models.CharField(max_length=20, blank=True)
    day138 = models.CharField(max_length=20, blank=True)
    day139 = models.CharField(max_length=20, blank=True)
    day140 = models.CharField(max_length=20, blank=True)
    day141 = models.CharField(max_length=20, blank=True)
    day142 = models.CharField(max_length=20, blank=True)
    day143 = models.CharField(max_length=20, blank=True)
    day144 = models.CharField(max_length=20, blank=True)
    day145 = models.CharField(max_length=20, blank=True)
    day146 = models.CharField(max_length=20, blank=True)
    day147 = models.CharField(max_length=20, blank=True)
    day148 = models.CharField(max_length=20, blank=True)
    day149 = models.CharField(max_length=20, blank=True)
    day150 = models.CharField(max_length=20, blank=True)
    day151 = models.CharField(max_length=20, blank=True)
    day152 = models.CharField(max_length=20, blank=True)
    day153 = models.CharField(max_length=20, blank=True)
    day154 = models.CharField(max_length=20, blank=True)
    day155 = models.CharField(max_length=20, blank=True)
    day156 = models.CharField(max_length=20, blank=True)
    day157 = models.CharField(max_length=20, blank=True)
    day158 = models.CharField(max_length=20, blank=True)
    day159 = models.CharField(max_length=20, blank=True)
    day160 = models.CharField(max_length=20, blank=True)
    day161 = models.CharField(max_length=20, blank=True)
    day162 = models.CharField(max_length=20, blank=True)
    day163 = models.CharField(max_length=20, blank=True)
    day164 = models.CharField(max_length=20, blank=True)
    day165 = models.CharField(max_length=20, blank=True)
    day166 = models.CharField(max_length=20, blank=True)
    day167 = models.CharField(max_length=20, blank=True)
    day168 = models.CharField(max_length=20, blank=True)
    day169 = models.CharField(max_length=20, blank=True)
    day170 = models.CharField(max_length=20, blank=True)
    day171 = models.CharField(max_length=20, blank=True)
    day172 = models.CharField(max_length=20, blank=True)
    day173 = models.CharField(max_length=20, blank=True)
    day174 = models.CharField(max_length=20, blank=True)
    day175 = models.CharField(max_length=20, blank=True)
    day176 = models.CharField(max_length=20, blank=True)
    day177 = models.CharField(max_length=20, blank=True)
    day178 = models.CharField(max_length=20, blank=True)
    day179 = models.CharField(max_length=20, blank=True)
    day180 = models.CharField(max_length=20, blank=True)
    day181 = models.CharField(max_length=20, blank=True)
    day182 = models.CharField(max_length=20, blank=True)
    day183 = models.CharField(max_length=20, blank=True)
    day184 = models.CharField(max_length=20, blank=True)
    day185 = models.CharField(max_length=20, blank=True)
    day186 = models.CharField(max_length=20, blank=True)
    day187 = models.CharField(max_length=20, blank=True)
    day188 = models.CharField(max_length=20, blank=True)
    day189 = models.CharField(max_length=20, blank=True)
    day190 = models.CharField(max_length=20, blank=True)
    day191 = models.CharField(max_length=20, blank=True)
    day192 = models.CharField(max_length=20, blank=True)
    day193 = models.CharField(max_length=20, blank=True)
    day194 = models.CharField(max_length=20, blank=True)
    day195 = models.CharField(max_length=20, blank=True)
    day196 = models.CharField(max_length=20, blank=True)
    day197 = models.CharField(max_length=20, blank=True)
    day198 = models.CharField(max_length=20, blank=True)
    day199 = models.CharField(max_length=20, blank=True)
    day200 = models.CharField(max_length=20, blank=True)
    day201 = models.CharField(max_length=20, blank=True)
    day202 = models.CharField(max_length=20, blank=True)
    day203 = models.CharField(max_length=20, blank=True)
    day204 = models.CharField(max_length=20, blank=True)
    day205 = models.CharField(max_length=20, blank=True)
    day206 = models.CharField(max_length=20, blank=True)
    day207 = models.CharField(max_length=20, blank=True)
    day208 = models.CharField(max_length=20, blank=True)
    day209 = models.CharField(max_length=20, blank=True)
    day210 = models.CharField(max_length=20, blank=True)
    day211 = models.CharField(max_length=20, blank=True)
    day212 = models.CharField(max_length=20, blank=True)
    day213 = models.CharField(max_length=20, blank=True)
    day214 = models.CharField(max_length=20, blank=True)
    day215 = models.CharField(max_length=20, blank=True)
    day216 = models.CharField(max_length=20, blank=True)
    day217 = models.CharField(max_length=20, blank=True)
    day218 = models.CharField(max_length=20, blank=True)
    day219 = models.CharField(max_length=20, blank=True)
    day220 = models.CharField(max_length=20, blank=True)
    day221 = models.CharField(max_length=20, blank=True)
    day222 = models.CharField(max_length=20, blank=True)
    day223 = models.CharField(max_length=20, blank=True)
    day224 = models.CharField(max_length=20, blank=True)
    day225 = models.CharField(max_length=20, blank=True)
    day226 = models.CharField(max_length=20, blank=True)
    day227 = models.CharField(max_length=20, blank=True)
    day228 = models.CharField(max_length=20, blank=True)
    day229 = models.CharField(max_length=20, blank=True)
    day230 = models.CharField(max_length=20, blank=True)
    day231 = models.CharField(max_length=20, blank=True)
    day232 = models.CharField(max_length=20, blank=True)
    day233 = models.CharField(max_length=20, blank=True)
    day234 = models.CharField(max_length=20, blank=True)
    day235 = models.CharField(max_length=20, blank=True)
    day236 = models.CharField(max_length=20, blank=True)
    day237 = models.CharField(max_length=20, blank=True)
    day238 = models.CharField(max_length=20, blank=True)
    day239 = models.CharField(max_length=20, blank=True)
    day240 = models.CharField(max_length=20, blank=True)
    day241 = models.CharField(max_length=20, blank=True)
    day242 = models.CharField(max_length=20, blank=True)
    day243 = models.CharField(max_length=20, blank=True)
    day244 = models.CharField(max_length=20, blank=True)
    day245 = models.CharField(max_length=20, blank=True)
    day246 = models.CharField(max_length=20, blank=True)
    day247 = models.CharField(max_length=20, blank=True)
    day248 = models.CharField(max_length=20, blank=True)
    day249 = models.CharField(max_length=20, blank=True)
    day250 = models.CharField(max_length=20, blank=True)
    day251 = models.CharField(max_length=20, blank=True)
    day252 = models.CharField(max_length=20, blank=True)
    day253 = models.CharField(max_length=20, blank=True)
    day254 = models.CharField(max_length=20, blank=True)
    day255 = models.CharField(max_length=20, blank=True)
    day256 = models.CharField(max_length=20, blank=True)
    day257 = models.CharField(max_length=20, blank=True)
    day258 = models.CharField(max_length=20, blank=True)
    day259 = models.CharField(max_length=20, blank=True)
    day260 = models.CharField(max_length=20, blank=True)
    day261 = models.CharField(max_length=20, blank=True)
    day262 = models.CharField(max_length=20, blank=True)
    day263 = models.CharField(max_length=20, blank=True)
    day264 = models.CharField(max_length=20, blank=True)
    day265 = models.CharField(max_length=20, blank=True)
    day266 = models.CharField(max_length=20, blank=True)
    day267 = models.CharField(max_length=20, blank=True)
    day268 = models.CharField(max_length=20, blank=True)
    day269 = models.CharField(max_length=20, blank=True)
    day270 = models.CharField(max_length=20, blank=True)
    day271 = models.CharField(max_length=20, blank=True)
    day272 = models.CharField(max_length=20, blank=True)
    day273 = models.CharField(max_length=20, blank=True)
    day274 = models.CharField(max_length=20, blank=True)
    day275 = models.CharField(max_length=20, blank=True)
    day276 = models.CharField(max_length=20, blank=True)
    day277 = models.CharField(max_length=20, blank=True)
    day278 = models.CharField(max_length=20, blank=True)
    day279 = models.CharField(max_length=20, blank=True)
    day280 = models.CharField(max_length=20, blank=True)
    day281 = models.CharField(max_length=20, blank=True)
    day282 = models.CharField(max_length=20, blank=True)
    day283 = models.CharField(max_length=20, blank=True)
    day284 = models.CharField(max_length=20, blank=True)
    day285 = models.CharField(max_length=20, blank=True)
    day286 = models.CharField(max_length=20, blank=True)
    day287 = models.CharField(max_length=20, blank=True)
    day288 = models.CharField(max_length=20, blank=True)
    day289 = models.CharField(max_length=20, blank=True)
    day290 = models.CharField(max_length=20, blank=True)
    day291 = models.CharField(max_length=20, blank=True)
    day292 = models.CharField(max_length=20, blank=True)
    day293 = models.CharField(max_length=20, blank=True)
    day294 = models.CharField(max_length=20, blank=True)
    day295 = models.CharField(max_length=20, blank=True)
    day296 = models.CharField(max_length=20, blank=True)
    day297 = models.CharField(max_length=20, blank=True)
    day298 = models.CharField(max_length=20, blank=True)
    day299 = models.CharField(max_length=20, blank=True)
    day300 = models.CharField(max_length=20, blank=True)
    day301 = models.CharField(max_length=20, blank=True)
    day302 = models.CharField(max_length=20, blank=True)
    day303 = models.CharField(max_length=20, blank=True)
    day304 = models.CharField(max_length=20, blank=True)
    day305 = models.CharField(max_length=20, blank=True)
    day306 = models.CharField(max_length=20, blank=True)
    day307 = models.CharField(max_length=20, blank=True)
    day308 = models.CharField(max_length=20, blank=True)
    day309 = models.CharField(max_length=20, blank=True)
    day310 = models.CharField(max_length=20, blank=True)
    day311 = models.CharField(max_length=20, blank=True)
    day312 = models.CharField(max_length=20, blank=True)
    day313 = models.CharField(max_length=20, blank=True)
    day314 = models.CharField(max_length=20, blank=True)
    day315 = models.CharField(max_length=20, blank=True)
    day316 = models.CharField(max_length=20, blank=True)
    day317 = models.CharField(max_length=20, blank=True)
    day318 = models.CharField(max_length=20, blank=True)
    day319 = models.CharField(max_length=20, blank=True)
    day320 = models.CharField(max_length=20, blank=True)
    day321 = models.CharField(max_length=20, blank=True)
    day322 = models.CharField(max_length=20, blank=True)
    day323 = models.CharField(max_length=20, blank=True)
    day324 = models.CharField(max_length=20, blank=True)
    day325 = models.CharField(max_length=20, blank=True)
    day326 = models.CharField(max_length=20, blank=True)
    day327 = models.CharField(max_length=20, blank=True)
    day328 = models.CharField(max_length=20, blank=True)
    day329 = models.CharField(max_length=20, blank=True)
    day330 = models.CharField(max_length=20, blank=True)
    day331 = models.CharField(max_length=20, blank=True)
    day332 = models.CharField(max_length=20, blank=True)
    day333 = models.CharField(max_length=20, blank=True)
    day334 = models.CharField(max_length=20, blank=True)
    day335 = models.CharField(max_length=20, blank=True)
    day336 = models.CharField(max_length=20, blank=True)
    day337 = models.CharField(max_length=20, blank=True)
    day338 = models.CharField(max_length=20, blank=True)
    day339 = models.CharField(max_length=20, blank=True)
    day340 = models.CharField(max_length=20, blank=True)
    day341 = models.CharField(max_length=20, blank=True)
    day342 = models.CharField(max_length=20, blank=True)
    day343 = models.CharField(max_length=20, blank=True)
    day344 = models.CharField(max_length=20, blank=True)
    day345 = models.CharField(max_length=20, blank=True)
    day346 = models.CharField(max_length=20, blank=True)
    day347 = models.CharField(max_length=20, blank=True)
    day348 = models.CharField(max_length=20, blank=True)
    day349 = models.CharField(max_length=20, blank=True)
    day350 = models.CharField(max_length=20, blank=True)
    day351 = models.CharField(max_length=20, blank=True)
    day352 = models.CharField(max_length=20, blank=True)
    day353 = models.CharField(max_length=20, blank=True)
    day354 = models.CharField(max_length=20, blank=True)
    day355 = models.CharField(max_length=20, blank=True)
    day356 = models.CharField(max_length=20, blank=True)
    day357 = models.CharField(max_length=20, blank=True)
    day358 = models.CharField(max_length=20, blank=True)
    day359 = models.CharField(max_length=20, blank=True)
    day360 = models.CharField(max_length=20, blank=True)
    day361 = models.CharField(max_length=20, blank=True)
    day362 = models.CharField(max_length=20, blank=True)
    day363 = models.CharField(max_length=20, blank=True)
    day364 = models.CharField(max_length=20, blank=True)
    day365 = models.CharField(max_length=20, blank=True)
    day366 = models.CharField(max_length=20, blank=True)

class threeyears(models.Model):
    d_id = models.CharField(max_length=50, primary_key=True)
    year1 = models.CharField(max_length=50, blank=True)
    year2 = models.CharField(max_length=50, blank=True)
    year3 = models.CharField(max_length=50, blank=True)

    
# class Videos(models.Model):
#     video = EmbedVideoField()


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)
